base:
  random_state : 36
  target_col : VISIBILITY
  test_size : 0.33

app:
  host : 0.0.0.0
  port : 8080 

data:
  raw_data:
    train_batch: training_data
    pred_batch: prediction_data

  train:
    good_data_dir : good/train
    bad_data_dir: bad/train

  pred:
    good_data_dir: good/pred
    bad_data_dir: bad/pred

mongodb:
  mongo_url: 
  climate_data_db_name: climate-data
  climate_train_data_collection: climate-train-data
  climate_pred_data_collection: climate-pred-data

knn_imputer:
  n_neighbors : 3
  weights : uniform
  missing_values: nan

kmeans_cluster:
  init          : k-means++
  max_clusters  : 11
  knee_locator:
    curve     : convex
    direction : decreasing

s3_bucket:
  input_files_bucket: input-files-for-train-and-pred
  climate_model_bucket: climate-model
  climate-mlflow_bucket: climate-mlflow
  climate_pred_data_bucket: climate-pred-data
  climate_train_data_bucket: climate-train-data
  climate_raw_data_bucket: climate-raw-data

models_dir:
  trained : trained/
  stag: staging/
  prod : production/

model_utils:
  verbose : 3
  cv      : 5
  n_jobs  : -1
  save_format : .sav

model_params:
  rf_model:
    n_estimators:
      - 10
      - 50
      - 100
      - 130
      
    criterion:
      - gini
      - entropy

    max_features:
      - auto
      - log2

    max_depth:
      - 2
      - 3
      - 4
      - 5

  xgb_model:
    learning_rate:
      - 0.5
      - 0.1
      - 0.01
      - 0.001

    max_depth:
      - 3
      - 5
      - 10
      - 20

    n_estimators:
      - 10
      - 50
      - 100
      - 200
    
mlflow_config:
  experiment_name : climate-ops
  run_name : mlops
  serialization_format : cloudpickle  

db_log:
  db_train_log : climate_training_logs
  db_pred_log : climate_prediction_logs

train_db_log:
  model_training : modelTrainingLog
  col_validation : columnValidationLog
  data_transform : dataTransform
  export_csv : ExportToCsvLog
  general : GeneralLog
  db_insert: dbInsertLog
  load_prod_model : loadProdModelLog
  missing_values_in_col : missingValuesInColumn
  name_validation : nameValidationLog
  train_main : Training_Main_Log
  values_from_schema : valuesfromSchemaValidationLog


pred_db_log:
  col_validation : columnValidationLog
  db_conn: databaseConnectionLog
  data_transform : dataTransform
  db_insert : dbInsertLog
  db_create : dbTableCreateLog
  export_csv : ExportToCsvLog
  general : GeneralLog
  missing_values_in_col : missingValuesInColumn
  name_validation : nameValidationLog
  pred_main : prediction_main_log
  values_from_schema : valuesfromSchemaValidationLog

schema_file:
  train_schema_file : schema_training.json
  pred_schema_file : schema_prediction.json
  
elbow_plot_fig : K-Means_Elbow.PNG

null_values_csv_file : null_values.csv

pred_output_file : predictions.csv

regex_file: climate_regex.txt

export_csv_file:
  train: train_input_file.csv
  pred: pred_input_file.csv

templates:
  dir : templates
  index_html_file : index.html